[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[colors.primary]
background = "#262626"
foreground = "#d4d4d4"

[colors.cursor]
text   = "#262626"
cursor = "#d4d4d4"

[colors.selection]
text       = "#262626"
background = "#ff99da"

[colors.normal]
black   = "#262626"
red     = "#ff99da"
green   = "#7acdcd"
yellow  = "#ff99da"
blue    = "#7acdcd"
magenta = "#ff99da"
cyan    = "#7acdcd"
white   = "#d4d4d4"

[colors.bright]
black   = "#444444"
red     = "#ff99da"
green   = "#7acdcd"
yellow  = "#ff99da"
blue    = "#7acdcd"
magenta = "#ff99da"
cyan    = "#7acdcd"
white   = "#ffffff"
